# /etc/knockd.conf
[options]
    UseSyslog
    Interface = ens6

[webprod]
    sequence       = 443,85,90
    seq_timeout    = 10
    start_command  = /sbin/iptables -t nat -A PREROUTING -s %IP% -p tcp --dport 443 -j DNAT --to-destination 10.10.10.1:5101
    cmd_timeout    = 60
    stop_command   = /sbin/iptables -t nat -D PREROUTING -s %IP% -p tcp --dport 443 -j DNAT --to-destination 10.10.10.1:5101
    tcpflags       = syn





