#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    client_body_buffer_size 1m;
    client_header_buffer_size 50k;
    client_max_body_size 10m;

    keepalive_timeout 65s;
    keepalive_requests 50;
    client_header_timeout 10s;
    client_body_timeout 100s;
    send_timeout 60s;

   server_tokens off;

    limit_req_zone $binary_remote_addr zone=req_limit_per_ip:10m rate=15r/s;
    limit_req zone=req_limit_per_ip burst=10 nodelay;

    # Configuracion de limitacion de conexiones
    limit_conn_zone $binary_remote_addr zone=conn_limit_per_ip:10m;
    limit_conn conn_limit_per_ip 10;


    #gzip  on;

    # HTTPS server
    server {
        listen       10.10.10.1:5101 ssl;
        server_name  platform.aspis.mx;

        ssl_certificate     /home/charlie/aspis.mx_ssl_certificate.pem;
        ssl_certificate_key  /home/charlie/aspis.mx_private_key.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }

}
