# sudo nano /etc/samba/smb.conf
# sudo apt install samba samba-common-bin -y
# sudo systemctl start smbd
# sudo systemctl start nmbd
[global]
        netbios name = TOMATOSERVER
        log file = /var/log/samba/%m.log
        log level = 1
        workgroup = SAMBA
        security = user
        printing = cups
        printcap name = cups
        load printers = yes
        cups options = raw

[Shared]
        comment = Home Directories
        path = /mnt/DC/Shared
        valid users = rosillo
        browseable = yes
        read only = no
        inherit acls = yes
        guest ok = no
        writable = yes
[ISOS]
        comment = ISOS
        path = /mnt/DC/ISOS
        valid users = rosillo
        browseable = yes
        read only = no
        inherit acls = yes
        guest ok = no
        writable = yes
[PICTURES]
        comment = ISOS
        path = /mnt/DCSSD/Cloud/PHONE_IMAGES
        valid users = rosillo
        browseable = yes
        read only = no
        inherit acls = yes
        guest ok = no
        writable = yes
       